### ISSUE TITLE
Cannot process table with gaps

### ISSUE THREAD

**Issue by vviital** [grodno-city/alis-web-request#71]
When I tried to download information about book with ```id = 46272```, I received such error message:
```
@grodno-city/alis-web-request/lib/index.js:220
uploader_1  |       value: el.children[1].children[0].data
uploader_1  |                                        ^
uploader_1  |
uploader_1  | TypeError: Cannot read property 'data' of undefined
uploader_1  |     at /home/app/lib/alis-web-index/node_modules/@grodno-city/alis-web-request/lib/index.js:220:40
uploader_1  |     at Array.forEach (native)
uploader_1  |     at collectFields (/home/app/lib/alis-web-index/node_modules/@grodno-city/alis-web-request/lib/index.js:215:8)
uploader_1  |     at getRecordInfo (/home/app/lib/alis-web-index/node_modules/@grodno-city/alis-web-request/lib/index.js:265:22)
uploader_1  |     at /home/app/lib/alis-web-index/node_modules/@grodno-city/alis-web-request/lib/index.js:277:16
uploader_1  |     at Request._callback (/home/app/lib/alis-web-index/node_modules/@grodno-city/alis-web-request/lib/index.js:82:5)
uploader_1  |     at Request.self.callback (/home/app/lib/alis-web-index/node_modules/request/request.js:188:22)
uploader_1  |     at emitTwo (events.js:125:13)
uploader_1  |     at Request.emit (events.js:213:7)
uploader_1  |     at Request.<anonymous> (/home/app/lib/alis-web-index/node_modules/request/request.js:1171:10)
```

**Comment by HannaKazello** [comment]
Fix in 1.1.2
